### ISSUE TITLE
Fix regexp to ignore color functions

### ISSUE THREAD

**Issue by zaim** [zzzaim/postcss-color-palette#3]
Current regexp matching erroneously replaces color-named functions, .e.g:

``` css
.test {
  color: gray(127);
  background: color(gray blue(+5));
}
```

Becomes

``` css
.test {
  color: #AAAAAA(120);
  background: color(#AAAAAA #0074D9(+5));
}
```

Very bad.
