### ISSUE TITLE
Deprecating this plugin

### ISSUE THREAD

**Issue by zaim** [zzzaim/postcss-color-palette#9]
I am thinking of deprecating this plugin in favor of simply using a combination of:
1. [postcss-custom-properties](https://github.com/postcss/postcss-custom-properties)
2. [postcss-import](https://github.com/postcss/postcss-import)
3. [webcolors](https://github.com/zaim/webcolors) (disclosure: this is also my project)

For example:

``` css
@import 'webcolors/material';  /* or 'webcolors/flatui' 'webcolors/mrmrs' */

body {
  color: var(--color-lime-a100);
  background: var(--color-indigo);
}
```

Because:
1. That's what I find myself doing
2. I rarely use simple base colors (e.g. green), instead I always find myself using Material color shades (e.g. lime-a100, etc)
3. I think this is more flexible, you have the entire palette at your disposal instead of only CSS color keywords
4. In the future (this feature is not yet implemented), you can import ALL color palettes at once:

``` css
@import 'webcolors';

body {
  color: var(--material-lime-a100);
  background: var(--flatui-midnight-blue);
}
```
